# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/7231/FPGADSP/vivado/voicechange/voicechange.srcs/sources_1/ip/InOutBuffer/InOutBuffer.xci
# IP: The module: 'InOutBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/7231/FPGADSP/vivado/voicechange/voicechange.srcs/sources_1/ip/InOutBuffer/InOutBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InOutBuffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: F:/7231/FPGADSP/vivado/voicechange/voicechange.srcs/sources_1/ip/InOutBuffer/InOutBuffer.xci
# IP: The module: 'InOutBuffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/7231/FPGADSP/vivado/voicechange/voicechange.srcs/sources_1/ip/InOutBuffer/InOutBuffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'InOutBuffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
